CREATE TABLE user
( userId INTEGER NOT NULL PRIMARY KEY,
username VARCHAR(20) NOT NULL,
password VARCHAR(30) NOT NULL,
joinDate DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
isModerator BIT DEFAULT 0 );

CREATE TABLE suspension 
( fromDate DATE NOT NULL PRIMARY KEY,
fromTime TIME NOT NULL PRIMARY KEY,
toDate DATE NOT NULL PRIMARY KEY,
toTime TIME NOT NULL PRIMARY KEY,
regular_userId INTEGER NOT NULL PRIMARY KEY,
moderator_userId INTEGER NOT NULL PRIMARY KEY,
FOREIGN KEY (regular_userId) REFERENCES user,
FOREIGN KEY (moderator_userId) REFERENCES user);

CREATE TABLE game
( gameId INTEGER NOT NULL PRIMARY KEY,
gameName VARCHAR(100) NOT NULL,
gameGenre VARCHAR(30) NOT NULL);

CREATE TABLE developer
( dId INTEGER NOT NULL PRIMARY KEY,
dName VARCHAR(100) NOT NULL,
founded DATE NOT NULL);

CREATE TABLE review
( rId INTEGER NOT NULL PRIMARY KEY,
description VARCHAR(3000),
rating INTEGER,
userId INTEGER NOT NULL,
gameId INTEGER NOT NULL,
FOREIGN KEY (userId, gameId) REFERENCES owns);

